Test all model on Radiogenomics Validation Cohort

In [8]:
import sklearn
from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve, auc, r2_score
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.metrics import precision_recall_curve, precision_score, average_precision_score, recall_score, f1_score

In [4]:
import pandas as pd
import numpy as np

In [13]:
data_results = pd.read_csv('../Data/radiomic_feature/val_results.csv')

val_tnbc_true = np.array(data_results['tnbc'])
val_caf_true = np.array(data_results['CAF'])
val_cd4_true = np.array(data_results['cd4'])
val_endo_true = np.array(data_results['Endo'])
val_macro_true = np.array(data_results['Macro'])

val_tnbc_pred = np.array(data_results['tnbc_pred'])
val_caf_pred = np.array(data_results['caf_pred5'])
val_cd4_pred = np.array(data_results['cd4_pred'])
val_endo_pred = np.array(data_results['Endo_pred'])
val_macro_pred = np.array(data_results['macro_pred'])


In [6]:
def cal_results(y_true, y_pred):

    fpr, tpr, thresholds = roc_curve(y_score=y_pred, y_true=y_true)
    roc_auc = auc(fpr, tpr)

    acc_con1 = confusion_matrix(y_pred=y_pred, y_true=y_true)
    acc_pred1 = accuracy_score(y_pred=y_pred, y_true=y_true)

    tn, fp, fn, tp = acc_con1.ravel()
    # Specificity
    spec_score = tn / (tn + fp) if (tn + fp) > 0 else 0 

    precision, recall, thresholds = precision_recall_curve(y_pred, y_true)
    pr_auc = auc(recall, precision)

    preci_scores = precision_score(y_pred=y_pred, y_true=y_true)
    recall_scores = recall_score(y_pred=y_pred, y_true=y_true)

    print("Accuracy Test: ", acc_pred1)
    print("Confusion Matrix: ")
    print(acc_con1) 
    print("ROC AUC: ", roc_auc)
    print("PR AUC: ", pr_auc)

    print('Recall / Sensitivity: ', recall_scores)
    print('Specificity: ', spec_score)


In [14]:
# TNBC VAL
cal_results(val_tnbc_true, val_tnbc_pred)

Accuracy Test:  1.0
Confusion Matrix: 
[[164   0]
 [  0  24]]
ROC AUC:  1.0
PR AUC:  1.0
Recall / Sensitivity:  1.0
Specificity:  1.0


In [15]:
# CAF VAL
cal_results(val_caf_true, val_caf_pred)

Accuracy Test:  0.8670212765957447
Confusion Matrix: 
[[83  0]
 [25 80]]
ROC AUC:  0.8809523809523809
PR AUC:  0.8809523809523809
Recall / Sensitivity:  0.7619047619047619
Specificity:  1.0


In [16]:
# CD4 VAL
cal_results(val_cd4_true, val_cd4_pred)

Accuracy Test:  0.5372340425531915
Confusion Matrix: 
[[45 16]
 [71 56]]
ROC AUC:  0.5893248999612752
PR AUC:  0.6519145213231325
Recall / Sensitivity:  0.4409448818897638
Specificity:  0.7377049180327869


In [17]:
# ENDO VAL
cal_results(val_endo_true, val_endo_pred)

Accuracy Test:  0.6914893617021277
Confusion Matrix: 
[[65 26]
 [32 65]]
ROC AUC:  0.6921944035346097
PR AUC:  0.7613433397048225
Recall / Sensitivity:  0.6701030927835051
Specificity:  0.7142857142857143


In [18]:
# MACRO VAL
cal_results(val_macro_true, val_macro_pred)

Accuracy Test:  0.5
Confusion Matrix: 
[[51 43]
 [51 43]]
ROC AUC:  0.5
PR AUC:  0.5930851063829787
Recall / Sensitivity:  0.4574468085106383
Specificity:  0.5425531914893617
